apiVersion: batch/v1
kind: Job
metadata:
  name: pi
spec:
  template:
    spec:
      containers:
      - name: pi
        image: lujoka/mub-csv-runner:latest
        imagePullPolicy: Always
        command: ["/app/entrypoint.sh", "--log-level", "DEBUG"]
      restartPolicy: Never
      volumes:
        - name: dataset
          persistentVolumeClaim:
            claimName: dataset
  backoffLimit: 4
