apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dataset
  labels:
    benchmark: input
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 4Gi
  storageClassName: local-storage
  selector:
    matchLabels:
      benchmark: input
