apiVersion: v1
kind: PersistentVolume
metadata:
  name: dataset
  labels:
    benchmark: input
spec:
  capacity:
    storage: 4Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /dataset
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          # node-2 -> the node with the dataset that contains:
          # * trace data
          # * service deployment timeline
          operator: In
          values:
          - node-2
