apiVersion: batch/v1
kind: Job
metadata:
  name: cloud-ee-benchmarking
  labels:
    benchmark: input
spec:
  template:
    spec:
      serviceAccountName: benchmark-sa
      initContainers:
      - name: builder
        image: lujoka/mub-k8s-templater:latest
        imagePullPolicy: Always
        command: ["/app/entrypoint.sh", "--log-level", "DEBUG", "-y"]
        volumeMounts:
        - name: dataset
          mountPath: "/dataset"
          readOnly: true
        - name: k8s-yaml
          mountPath: "/k8s-yaml"
          readOnly: false
      containers:
      - name: runner
        image: lujoka/mub-csv-runner:latest
        imagePullPolicy: Always
        # The actual command
        # command: ["/app/entrypoint.sh"]
        # Sleep command so we can exec into the container and see all file paths work
        command: ["/bin/bash", "-c", "--"]
        args: [ "while true; do sleep 30; done;" ]
        volumeMounts:
        - name: dataset
          mountPath: "/dataset"
          readOnly: true
        - name: k8s-yaml
          mountPath: "/k8s-yaml"
          readOnly: true
        - name: runner-params
          mountPath: "/config"
        - name: result
          mountPath: "/result"
          readOnly: false
      restartPolicy: Never
      volumes:
        - name: dataset
          persistentVolumeClaim:
            claimName: dataset
        - name: result
          persistentVolumeClaim:
            claimName: result
        - name: k8s-yaml
          emptyDir: {}
        - name: runner-params
          configMap:
            name: csv-runner-params
  backoffLimit: 1
